service: notification

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  logRetentionInDays: 5
  region: us-east-1
  memorySize: 512
  stage: dev

  environment:
    snsARN: set-arn
    RECIPIENT_ALERT: ${self:custom.recipientAlert}
    SENDER_ALERT: ${self:custom.senderAlert}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: 
        - arn:aws:ses:${self:provider.region}:${aws:accountId}:identity/*



functions:
  user_scan_log:
    handler: alert_handler.user_scan_log
    description: Send an email based an exception when inventory process throw an error for SAVA project
    events:
      - cloudwatchLog: 
          logGroup: '/aws/lambda/users-${opt:stage, self:provider.stage}-createProfile'
          filter: 'User_Source_Error'

  profile_scan_log:
    handler: alert_handler.profile_scan_log
    description: Send an email based an exception when price process throw an error for SAVA project
    events:
      - cloudwatchLog:
          logGroup: '/aws/lambda/users-${opt:stage, self:provider.stage}-getUser'
          filter: 'Profile_Source_Error'



custom:
  recipientAlert: 'jperez@gmail.com'
  senderAlert: 'jperez@gmail.com'

